# Generated by Django 4.2 on 2023-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projectimages_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(null=True, to='portfolio.category', verbose_name='Категория'),
        ),
    ]
